---
title: "p8105_hw1_ml4424"
author: "Maggie Li (ml4424)"
date: "9/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

## Problem 1

```{r}
# create df

p1_df <- tibble(
  samp = rnorm(10),
  log_vec = samp > 0,
  char_vec = c("a", "b", "c", "d", "e","f", "g", "h", "i", "j"),
  fac_vec = factor(c("bananas", "oranges", "apples",
                    "bananas", "oranges", "apples",
                    "bananas", "oranges", "apples",
                    "bananas")))
p1_df

# you can take the mean of samp, log_vec (I am assuming since it is a vector of binary numeric values, T = 1 and F = 0 values) since these are continuous variables, but cannot take mean of characters or factors since these are categorical variables

```

```{r}
as.numeric(p1_df$log_vec)
as.numeric(p1_df$char_vec)
mean(as.numeric(p1_df$fac_vec))

# as.numeric works with logical and factor variables. it is because the logical vector consists of binary numeric values T=1 and F=0, and factor variables are categorical variables but when converted to numeric they get coerced to numbered levels. this helps to explain why mean works with logical vectors, but not factor variables until they are coerced to numeric.
```

```{r}
as.numeric(p1_df$log_vec) * p1_df$samp 
# this works because log_vec is easily coerced to numeric, T=1 and F=0

as.factor(p1_df$log_vec) * p1_df$samp
# T and F values get coded as factors; 2 levels

as.numeric(as.factor(p1_df$log_vec)) * p1_df$samp
# T gets coded as 2 and False as 1 for numeric, and can multiple it by another numeric
```

